server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 백엔드 API 프록시
    location /api/ {
        proxy_pass http://backend:8181/backend_logic/;
    }
}